fun testing(): i32 {
    return 2
}

@Packed // Omits any padding and allows specifying bitfields in a struct
pub struct Foo {
    pub mut x: i20
    pub mut y: i10
    pub mut z: i2

    pub struct Bar { // Nested type declarations
        value: bool
    }
}

fun bar(value: Foo&, value2: Foo::Bar&) {
}

pub attrib Test {
    pub value: i32
    pub flag: bool
}

@Test(flag = true, value = 100)
pub attrib AnotherAttrib {
    pub value: string
}

@NoMangle
@Test(flag = true, value = 100)
fun main(num_args: i32, args: char**): i32 {
    let x: i32 = num_args
    let mut y = &x
    let z = *y
    let mut cond = true
    return cond ? z : 0
}