fun testing(): i32 {
    return 2
}

@Packed // Omits any padding and allows specifying bitfields in a struct
pub struct Foo {
    pub x: i20
    pub y: i10
    pub z: i2

    pub struct Bar { // Nested type declarations
        value: bool
    }
}

fun bar(value: Foo&, value2: Foo::Bar&) {
}

pub attrib Test {
    pub value: i32
    pub flag: bool
}

@Test(flag = true, value = 100)
pub attrib AnotherAttrib {
    pub value: string
}

@NoMangle
@Test(flag = true, value = 100)
fun main(num_args: i32, args: char**): i32 {
    let mut x: i32 = num_args
    let mut y: mut i32* = &x
    let mut cond = false
    return cond ? x : 0
}