// stdio.h
type FileHandle = void*

fun remove(name: char*): i32
fun rename(old_name: char*, new_name: char*): i32
fun tmpfile(): FileHandle
fun tmpnam(str: mut char*): mut char*
fun fclose(handle: FileHandle): i32
fun fflush(handle: FileHandle): i32
fun fopen(name: char*, mode: char*): FileHandle
fun freopen(name: char*, mode: char*, handle: FileHandle): FileHandle
fun setbuf(handle: FileHandle, buffer: char*)
fun setvbuf(handle: FileHandle, buffer: char*, mode: i32, size: usize): i32